name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          access-token: ${{ secrets.GH_PAGES }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
